# Generated by Django 3.1.1 on 2022-03-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sex',
            field=models.PositiveBigIntegerField(choices=[(0, 'Female'), (1, 'Male')], null=True),
        ),
    ]
